### ISSUE TITLE
Run from .sh file

### ISSUE THREAD

**Issue by Cyberavater** [jaredrummler/AndroidShell#21]
Can I execute .sh files? If yes, can you link me to that guide? Thanks!

**Comment by Tanzin01** [comment]
Did you succeed getting root permission?. in my case even though i gave the app root acceess, but cant create folder due to permission denied.

**Comment by Tanzin01** [comment]
you can. learn /searchabout how to give/make a file executable. then execute

**Comment by Tanzin01** [comment]
i had to waste a lots of time..... many manny after many test and trials.
Add #!/system/bin/sh to your file(i forget and had to waste 30around min)
i had may wasted 4 hours around>> once worked, and never worked, this and that.. No erro yet nothing is happening was the most pain and etc.

Keep your file in /data/bin
If you get permission error, add su.
Other error dont know.

**Comment by Cyberavater** [comment]
> you can. learn /searchabout how to give/make a file executable. then execute

Provide a sample, please.

**Comment by Tanzin01** [comment]
Sure:) i had some rough time fiigure things out.
Lets say you have a file named myfile.sh in /storage/emylated/.../myfile.sh.

Now make it executable- 
chmod +x /storage/emylated/.../myfile.sh
Now run it-
Shell.SU.run("/storage/emylated/.../myfile.sh")

[for non root, i dont know since sid not tried. you needa figure out(perhaps run with Shell.run("/storage/emylated/.../myfile.sh")]

**Comment by Cyberavater** [comment]
Okay, thanks for your time. I'll try it out and come back if I need more help. Thanks.
